---
title: "P8105 Homework 2"
author: "Junxian Chen ( jc5314 )"
date: "9/27/2019"
output: github_document
---

# Problem 1

### Part 1: Read and clean the Mr. Trash Wheel sheet

Firstly, load nessary libraries:

```{r, message = FALSE}
library(tidyverse)
library(readxl)
```

Next, read in the data as `trash_wheel_data` and do the clean:

```{r}
file_path = './data/HealthyHarborWaterWheelTotals2018-7-28.xlsx'

trash_wheel_data = 
  read_excel(file_path, sheet = 'Mr. Trash Wheel', range = cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = as.integer(round(sports_balls))
  )
```

### Part 2: Read and clean precipitation data for 2017 and 2018

```{r}
# Read and clean precipitation data for 2017

pre_2017_data = 
  read_excel(file_path, sheet = '2017 Precipitation', skip = 1) %>%
  janitor::clean_names() %>% 
  drop_na(total)  %>% 
  mutate(year = 2017)
  
```

```{r}
# Read and clean precipitation data for 2018

pre_2018_data = 
  read_excel(file_path, sheet = '2018 Precipitation', skip = 1) %>%
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018)
```

```{r, message = FALSE}
# Combine precipitation datasets and convert month to a character variable

pre_2017_18 = 
  full_join(pre_2017_data, pre_2018_data) %>%
  mutate(month = month.name[month]) %>%
  replace_na(list(month = 'Sum'))

pre_2017_18
```

### Part 3: Brief information about these data


